kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  # these labels are deployment related labels 
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: ramudevops321/mysql:v1.0
  
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port